//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace ControlPanel { namespace AirPurifier {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IAirPurifierService. Instead, AirPurifierServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class AirPurifierServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IAirPurifierService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierPowerONCalledEventArgs^>^ PowerONCalled;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierPowerOFFCalledEventArgs^>^ PowerOFFCalled;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierResetCalledEventArgs^>^ ResetCalled;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierSendSoftwareUpgradeFileCalledEventArgs^>^ SendSoftwareUpgradeFileCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetPowerStatusRequestedEventArgs^>^ GetPowerStatusRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetFlowValueRequestedEventArgs^>^ GetFlowValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetTimerValueRequestedEventArgs^>^ GetTimerValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorOdorValueRequestedEventArgs^>^ GetSensorOdorValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorDustValueRequestedEventArgs^>^ GetSensorDustValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorAllergenValueRequestedEventArgs^>^ GetSensorAllergenValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorCleanMetalGridValueRequestedEventArgs^>^ GetSensorCleanMetalGridValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorReplaceFilterValueRequestedEventArgs^>^ GetSensorReplaceFilterValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierGetSensorCleanMonitorValueRequestedEventArgs^>^ GetSensorCleanMonitorValueRequested;
    
    // Property Write Events
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierSetPowerStatusRequestedEventArgs^>^ SetPowerStatusRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierSetFlowValueRequestedEventArgs^>^ SetFlowValueRequested;
    event Windows::Foundation::TypedEventHandler<AirPurifierServiceEventAdapter^, AirPurifierSetTimerValueRequestedEventArgs^>^ SetTimerValueRequested;

    // IAirPurifierService Implementation
    virtual Windows::Foundation::IAsyncOperation<AirPurifierPowerONResult^>^ PowerONAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierPowerOFFResult^>^ PowerOFFAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierResetResult^>^ ResetAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierSendSoftwareUpgradeFileResult^>^ SendSoftwareUpgradeFileAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 interfaceMemberCurrentIndex, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberFileData);

    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetPowerStatusResult^>^ GetPowerStatusAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetFlowValueResult^>^ GetFlowValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetTimerValueResult^>^ GetTimerValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorOdorValueResult^>^ GetSensorOdorValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorDustValueResult^>^ GetSensorDustValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorAllergenValueResult^>^ GetSensorAllergenValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorCleanMetalGridValueResult^>^ GetSensorCleanMetalGridValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorReplaceFilterValueResult^>^ GetSensorReplaceFilterValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierGetSensorCleanMonitorValueResult^>^ GetSensorCleanMonitorValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<AirPurifierSetPowerStatusResult^>^ SetPowerStatusAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ int32 value);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierSetFlowValueResult^>^ SetFlowValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ int32 value);
    virtual Windows::Foundation::IAsyncOperation<AirPurifierSetTimerValueResult^>^ SetTimerValueAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ int32 value);
};

} } } } 
