//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace AirPurifier { namespace Actions {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IActionsService. Instead, ActionsServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class ActionsServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IActionsService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetPowerToOffCalledEventArgs^>^ SetPowerToOffCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetPowerToOnCalledEventArgs^>^ SetPowerToOnCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetFlowToHICalledEventArgs^>^ SetFlowToHICalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetFlowToMEDCalledEventArgs^>^ SetFlowToMEDCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetFlowToLOWCalledEventArgs^>^ SetFlowToLOWCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetFlowToQUIETCalledEventArgs^>^ SetFlowToQUIETCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetFlowToAUTOCalledEventArgs^>^ SetFlowToAUTOCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetTimerTo8HCalledEventArgs^>^ SetTimerTo8HCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetTimerTo2HCalledEventArgs^>^ SetTimerTo2HCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetTimerTo1HCalledEventArgs^>^ SetTimerTo1HCalled;
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsSetTimerToOffCalledEventArgs^>^ SetTimerToOffCalled;

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<ActionsServiceEventAdapter^, ActionsGetVersionRequestedEventArgs^>^ GetVersionRequested;
    
    // Property Write Events

    // IActionsService Implementation
    virtual Windows::Foundation::IAsyncOperation<ActionsSetPowerToOffResult^>^ SetPowerToOffAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetPowerToOnResult^>^ SetPowerToOnAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetFlowToHIResult^>^ SetFlowToHIAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetFlowToMEDResult^>^ SetFlowToMEDAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetFlowToLOWResult^>^ SetFlowToLOWAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetFlowToQUIETResult^>^ SetFlowToQUIETAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetFlowToAUTOResult^>^ SetFlowToAUTOAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetTimerTo8HResult^>^ SetTimerTo8HAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetTimerTo2HResult^>^ SetTimerTo2HAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetTimerTo1HResult^>^ SetTimerTo1HAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<ActionsSetTimerToOffResult^>^ SetTimerToOffAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<ActionsGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
