//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace AirPurifier { namespace Actions {

ref class ActionsConsumer;

public ref class ActionsSetPowerToOffResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetPowerToOffResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetPowerToOffResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetPowerToOffResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetPowerToOffResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetPowerToOnResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetPowerToOnResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetPowerToOnResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetPowerToOnResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetPowerToOnResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetFlowToHIResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetFlowToHIResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetFlowToHIResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetFlowToHIResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetFlowToHIResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetFlowToMEDResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetFlowToMEDResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetFlowToMEDResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetFlowToMEDResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetFlowToMEDResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetFlowToLOWResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetFlowToLOWResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetFlowToLOWResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetFlowToLOWResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetFlowToLOWResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetFlowToQUIETResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetFlowToQUIETResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetFlowToQUIETResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetFlowToQUIETResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetFlowToQUIETResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetFlowToAUTOResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetFlowToAUTOResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetFlowToAUTOResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetFlowToAUTOResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetFlowToAUTOResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetTimerTo8HResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetTimerTo8HResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetTimerTo8HResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetTimerTo8HResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetTimerTo8HResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetTimerTo2HResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetTimerTo2HResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetTimerTo2HResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetTimerTo2HResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetTimerTo2HResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetTimerTo1HResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetTimerTo1HResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetTimerTo1HResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetTimerTo1HResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetTimerTo1HResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsSetTimerToOffResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static ActionsSetTimerToOffResult^ CreateSuccessResult()
    {
        auto result = ref new ActionsSetTimerToOffResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static ActionsSetTimerToOffResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsSetTimerToOffResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class ActionsJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property ActionsConsumer^ Consumer
    {
        ActionsConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ ActionsConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    ActionsConsumer^ m_consumer;
};

public ref class ActionsGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static ActionsGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new ActionsGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        return result;
    }

    static ActionsGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new ActionsGetVersionResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    uint16 m_value;
};

} } } } 
