//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace AirPurifier { namespace Actions {

public interface class IActionsService
{
public:
    // Implement this function to handle calls to the SetPowerToOff method.
    Windows::Foundation::IAsyncOperation<ActionsSetPowerToOffResult^>^ SetPowerToOffAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetPowerToOn method.
    Windows::Foundation::IAsyncOperation<ActionsSetPowerToOnResult^>^ SetPowerToOnAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetFlowToHI method.
    Windows::Foundation::IAsyncOperation<ActionsSetFlowToHIResult^>^ SetFlowToHIAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetFlowToMED method.
    Windows::Foundation::IAsyncOperation<ActionsSetFlowToMEDResult^>^ SetFlowToMEDAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetFlowToLOW method.
    Windows::Foundation::IAsyncOperation<ActionsSetFlowToLOWResult^>^ SetFlowToLOWAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetFlowToQUIET method.
    Windows::Foundation::IAsyncOperation<ActionsSetFlowToQUIETResult^>^ SetFlowToQUIETAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetFlowToAUTO method.
    Windows::Foundation::IAsyncOperation<ActionsSetFlowToAUTOResult^>^ SetFlowToAUTOAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetTimerTo8H method.
    Windows::Foundation::IAsyncOperation<ActionsSetTimerTo8HResult^>^ SetTimerTo8HAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetTimerTo2H method.
    Windows::Foundation::IAsyncOperation<ActionsSetTimerTo2HResult^>^ SetTimerTo2HAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetTimerTo1H method.
    Windows::Foundation::IAsyncOperation<ActionsSetTimerTo1HResult^>^ SetTimerTo1HAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SetTimerToOff method.
    Windows::Foundation::IAsyncOperation<ActionsSetTimerToOffResult^>^ SetTimerToOffAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle requests for the value of the Version property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<ActionsGetVersionResult^>^ GetVersionAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
