//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace ControlPanel { namespace Humidifier {

ref class HumidifierConsumer;

public ref class HumidifierPowerONResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static HumidifierPowerONResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierPowerONResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static HumidifierPowerONResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierPowerONResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierPowerOFFResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static HumidifierPowerOFFResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierPowerOFFResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static HumidifierPowerOFFResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierPowerOFFResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierSendSoftwareUpgradeFileResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static HumidifierSendSoftwareUpgradeFileResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSendSoftwareUpgradeFileResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static HumidifierSendSoftwareUpgradeFileResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSendSoftwareUpgradeFileResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property HumidifierConsumer^ Consumer
    {
        HumidifierConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ HumidifierConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    HumidifierConsumer^ m_consumer;
};

public ref class HumidifierGetPowerStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 PowerStatus
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetPowerStatusResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetPowerStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->PowerStatus = value;
        return result;
    }

    static HumidifierGetPowerStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetPowerStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetPowerStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetPowerStatusResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetPowerStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetPowerStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetPowerStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetHumidityValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 HumidityValue
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetHumidityValueResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetHumidityValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->HumidityValue = value;
        return result;
    }

    static HumidifierGetHumidityValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetHumidityValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetHumidityValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetHumidityValueResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetHumidityValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetHumidityValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetHumidityValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetIonStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 IonStatus
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetIonStatusResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetIonStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->IonStatus = value;
        return result;
    }

    static HumidifierGetIonStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetIonStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetIonStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetIonStatusResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetIonStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetIonStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetIonStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetWarmMistStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 WarmMistStatus
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetWarmMistStatusResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetWarmMistStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->WarmMistStatus = value;
        return result;
    }

    static HumidifierGetWarmMistStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetWarmMistStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetWarmMistStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetWarmMistStatusResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetWarmMistStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetWarmMistStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetWarmMistStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetMistVolumeValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 MistVolumeValue
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetMistVolumeValueResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetMistVolumeValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MistVolumeValue = value;
        return result;
    }

    static HumidifierGetMistVolumeValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetMistVolumeValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetMistVolumeValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetMistVolumeValueResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetMistVolumeValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetMistVolumeValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetMistVolumeValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetTimerValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 TimerValue
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetTimerValueResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetTimerValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->TimerValue = value;
        return result;
    }

    static HumidifierGetTimerValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetTimerValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierSetTimerValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static HumidifierSetTimerValueResult^ CreateSuccessResult()
    {
        auto result = ref new HumidifierSetTimerValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }

    static HumidifierSetTimerValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierSetTimerValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class HumidifierGetCurrentRoomTempValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 CurrentRoomTempValue
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetCurrentRoomTempValueResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetCurrentRoomTempValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->CurrentRoomTempValue = value;
        return result;
    }

    static HumidifierGetCurrentRoomTempValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetCurrentRoomTempValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierGetCurrentRoomHumidityValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 CurrentRoomHumidityValue
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetCurrentRoomHumidityValueResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetCurrentRoomHumidityValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->CurrentRoomHumidityValue = value;
        return result;
    }

    static HumidifierGetCurrentRoomHumidityValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetCurrentRoomHumidityValueResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

public ref class HumidifierGetWaterTankStatusResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int32 WaterTankStatus
    {
        int32 get() { return m_value; }
    internal:
        void set(_In_ int32 value) { m_value = value; }
    }

    static HumidifierGetWaterTankStatusResult^ CreateSuccessResult(_In_ int32 value)
    {
        auto result = ref new HumidifierGetWaterTankStatusResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->WaterTankStatus = value;
        return result;
    }

    static HumidifierGetWaterTankStatusResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new HumidifierGetWaterTankStatusResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
    int32 m_value;
};

} } } } 
