//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace ControlPanel { namespace Humidifier {

// Signals
public ref class HumidifierCurrentRoomTempValueChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewCurrentRoomTempValue
    {
        int32 get() { return m_interfaceMemberNewCurrentRoomTempValue; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewCurrentRoomTempValue = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewCurrentRoomTempValue;
};

public ref class HumidifierCurrentRoomHumidityValueChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewCurrentRoomHumidityValue
    {
        int32 get() { return m_interfaceMemberNewCurrentRoomHumidityValue; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewCurrentRoomHumidityValue = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewCurrentRoomHumidityValue;
};

public ref class HumidifierWaterTankStatusChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewWaterTankStatus
    {
        int32 get() { return m_interfaceMemberNewWaterTankStatus; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewWaterTankStatus = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewWaterTankStatus;
};

public ref class HumidifierPowerStatusChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewPowerStatus
    {
        int32 get() { return m_interfaceMemberNewPowerStatus; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewPowerStatus = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewPowerStatus;
};

public ref class HumidifierHumidityValueChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewHumidityValue
    {
        int32 get() { return m_interfaceMemberNewHumidityValue; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewHumidityValue = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewHumidityValue;
};

public ref class HumidifierIonStatusChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewIonStatus
    {
        int32 get() { return m_interfaceMemberNewIonStatus; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewIonStatus = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewIonStatus;
};

public ref class HumidifierWarmMistStatusChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewWarmMistStatus
    {
        int32 get() { return m_interfaceMemberNewWarmMistStatus; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewWarmMistStatus = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewWarmMistStatus;
};

public ref class HumidifierMistVolumeValueChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewMistVolumeValue
    {
        int32 get() { return m_interfaceMemberNewMistVolumeValue; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewMistVolumeValue = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewMistVolumeValue;
};

public ref class HumidifierTimerValueChangedReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property int32 NewTimerValue
    {
        int32 get() { return m_interfaceMemberNewTimerValue; }
    internal:
        void set(_In_ int32 value) { m_interfaceMemberNewTimerValue = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    int32 m_interfaceMemberNewTimerValue;
};


} } } } 
