//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace ControlPanel { namespace Humidifier {

public interface class IHumidifierService
{
public:
    // Implement this function to handle calls to the PowerON method.
    Windows::Foundation::IAsyncOperation<HumidifierPowerONResult^>^ PowerONAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the PowerOFF method.
    Windows::Foundation::IAsyncOperation<HumidifierPowerOFFResult^>^ PowerOFFAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the SendSoftwareUpgradeFile method.
    Windows::Foundation::IAsyncOperation<HumidifierSendSoftwareUpgradeFileResult^>^ SendSoftwareUpgradeFileAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint32 interfaceMemberCurrentIndex, _In_ Windows::Foundation::Collections::IVectorView<byte>^ interfaceMemberFileData);

    // Implement this function to handle requests for the value of the powerStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetPowerStatusResult^>^ GetPowerStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the powerStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetPowerStatusResult^>^ SetPowerStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the humidityValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetHumidityValueResult^>^ GetHumidityValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the humidityValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetHumidityValueResult^>^ SetHumidityValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the ionStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetIonStatusResult^>^ GetIonStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the ionStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetIonStatusResult^>^ SetIonStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the warmMistStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetWarmMistStatusResult^>^ GetWarmMistStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the warmMistStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetWarmMistStatusResult^>^ SetWarmMistStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the mistVolumeValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetMistVolumeValueResult^>^ GetMistVolumeValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the mistVolumeValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetMistVolumeValueResult^>^ SetMistVolumeValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the timerValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetTimerValueResult^>^ GetTimerValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the timerValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierSetTimerValueResult^>^ SetTimerValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int32 value);

    // Implement this function to handle requests for the value of the currentRoomTempValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetCurrentRoomTempValueResult^>^ GetCurrentRoomTempValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the currentRoomHumidityValue property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetCurrentRoomHumidityValueResult^>^ GetCurrentRoomHumidityValueAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the waterTankStatus property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<HumidifierGetWaterTankStatusResult^>^ GetWaterTankStatusAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
